zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      #we can use url or serviceId. if there is eureka-service at back-end use url else serviceId=HELLO-SERVER
      url: http://localhost:8061
    hello-client:
      path: /client/**
      serviceId: HELLO-CLIENT

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8060/eureka/
  instance:
    hostname: localhost

server:
  port: 8059

spring:
  application:
    name: zuul-service

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
timeoutInMilliseconds: 60000